######################################################################
# Automatically generated by qmake (3.0) ?? 6? 21 17:38:56 2014
######################################################################

QT       += core gui sql

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = POS_system
TEMPLATE = app


SOURCES += main.cpp\
        widget.cpp \
    work.cpp \
    pay.cpp

HEADERS  += widget.h \
    work.h \
    pay.h

FORMS    += widget.ui work.ui pay.ui
